services:
nginx:
image: nginx:latest
ports:
- "80:80"
volumes:
- ./nginx/nginx.conf:/etc/nginx/nginx.conf
- ./app/uploads:/var/www/uploads
- ./app/generated:/var/www/generated
depends_on:
- api


api:
build: ./app
container_name: techno_ai_api
volumes:
- ./app/uploads:/app/uploads
- ./app/generated:/app/generated
- ./app/checkpoints:/app/checkpoints
ports:
- "8000:8000"